### ISSUE TITLE
main page Volume Button

### ISSUE THREAD

**Issue by jurjenwork** [murderbeard/com.moz.denon#12] opened 2020-07-11 09:35 UTC
loving the app but there is one thing i really hate; the main page shows the volume which is fine but when you press the "+" button it instantly jumps to 100%. I literally almost blew up my speakers and became deaf. As you can understand this is a pretty dangerous button. 

Was wondering if you could either remove this option or make it jump like 5% at a time rather than setting the volume to 100%?

Thanks and keep up the great app!

**Comment by murderbeard** [comment] 2020-07-11 10:10
Hi Jurjen,

That's definitely annoying. I remember having a similar issue when first making the app; it was related to the avr getting a volume set request that was out of a valid range and deciding to just put it at 100%. 

Are you able to reproduce this problem easily? I'd like to know what volume the avr is set to originally before pressing the button or does it always happen regardless of the level? Also what is your avr volume display set to: dB or percentage? My own is set to dB and I haven't changed it to percentages since early development. I don't recall this changing the communications protocol at all but just to be sure. Do the volume adjust flow cards work properly for you? Specifically the relative volume adjust card.

Hope to have fixed this ASAP as this is quite crappy to happen when using the app.

Regards,
Ralph

**Comment by jurjenwork** [comment] 2020-07-11 10:30
hello!

thanks a bunch for your lightning fast response.

yes I can reproduce this indeed. Even when the AVR is turned off and I press on the "+"in the main screen it jumps to 100% (in the app of course). So it does not matter what initial volume it is set to.

The volume is set to DB. I do not really use the adjust cards in flows so I cannot tell you but if you use the slide bar in the main page underneath the "+" I can adjust the volume properly so that is working nicely. Does this help?

**Comment by murderbeard** [comment] 2020-07-11 19:47
Hi,

It's pretty weird but I do get exactly the same issue here as well. It seems the (+ & -) buttons at the slider do not make use of the volume_up and volume_down capabilities which are on another page (together with the mute button). Those work fine but for some reason the slider buttons just jump it 1.0 and 0.0 which are max and min. If I change the slider values to say 980 and 0 the same still happens. And there don't seem to be any other options to change the slider settings (such as step size). Will have to investigate a bit further.

**Comment by jurjenwork** [comment] 2020-07-11 19:52
Good to see that I am not the only one :)!

A quick fix would even be to disable the + and - buttons on the slider page entirely. Just the slider on that page is enough and if one wants to use buttons they can swipe to the next page on the device, right?

**Comment by murderbeard** [comment] 2023-02-12 12:21
This issue is finally fixed in a future release of Homey. It was an internal homey issue that I couldn't fix myself without removing the slider altogether. Expect this to be fixed in a future release of the Homey software.

**Closed by murderbeard** 2023-02-12 12:21 UTC
